### ISSUE TITLE
v4 Guid syntax

### ISSUE THREAD

**Issue by d4hines** [TrekkingForCharity/ts-odata#1]
As of v4, guids are no longer prefixed by "guid'value'". Instead, they are just a literal "value". There needs to at least be an option for casting a guid in the v4 format. 
http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398153

**Comment by d4hines** [comment]
Closed by PR #2 .

**Comment by d4hines** [comment]
At some point, can a new build that in corporates PR #2  be pushed to the npm registry? The npm client doesn't seem to handle dependancies on GitHub quite as gracefully.

**Comment by roly445** [comment]
published to npm
